### ISSUE TITLE
Initialize Next.js Project

### ISSUE THREAD

**Issue by sub1120** [Vision-Clara/visionclara#1]
Live Link - https://visionclara.in/

**Comment by sharadmehra697** [comment]
Ok we can go through the setup once done by your side.

**Comment by sub1120** [comment]
Ya Sure, we can have meet.

**Comment by sub1120** [comment]
A problem guys, to use Next.js Dynamic routing feature, we need GCP Cloud Function service enabled. Will discuss in meeting.
